### ISSUE TITLE
Requesting a guide for running the Script

### ISSUE THREAD

**Issue by phoenixml** [B0fH/yara-suricata#1]
Hi I placed the rule into the appropriate folder and run the script but nothing occurred:
lua yara.lua

any help would be appreciated

**Comment by B0fH** [comment]
Good point, I'll update the readme. In order to use this script, you'll need a working [Suricata](https://suricata-ids.org/) installation compiled with Lua support. The script will need to be placed in the Suricata output scripts directory, and specified by name in output scripts section in the Suricata config file(suricata.yaml). Please see https://suricata.readthedocs.io/en/latest/output/lua-output.html#yaml for the correct syntax.

Thanks,
 Elazar

**Comment by tee2015** [comment]
Hi Elazar,
1- Suricata compiled with Lua and I confirmed that via command : suricata  --build  / Luajit enabled:yes
2- script placed under /etc/suricata/lua-output/yara.lua
3- I updated the script to be included in the Suricata.yaml output
 - lua:
      enabled: yes
      scripts-dir: /etc/suricata/lua-output/
      scripts:
        - yara.lua

my question should I create a suricata rule that will call the script using lujit? or just its enought to include the script in the suricata as I know from previous lusa scripts that I must include the script within suricata rules? thank you for your help and clarification appreciated.
